/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2017-01-11 07:32:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import metier.JeuPileOuFace;

public final class jeu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write(" \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title> Jeu </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <center>\n");
      out.write("    <h1>Pile ou Face</h1>\n");
      out.write("    ");
 JeuPileOuFace jeu = (JeuPileOuFace)session.getAttribute("PileFace");
       if (jeu==null){
       jeu = new JeuPileOuFace();
       jeu.init();
       session.setAttribute("PileFace",jeu);
       } 
      out.write("\n");
      out.write("    Le premier arrivé à 10 a gagné !<br>\n");
      out.write("    Deux faces identiques, je gagne, deux faces différentes, vous gagnez !<br>\n");
      out.write("    <br>\n");
      out.write("    ");
 String choix = request.getParameter("choix");
       if(choix == null){ 
      out.write("\n");
      out.write("    Nous allons débuter une nouvelle partie<br>\n");
      out.write("    ");
 } else if(choix.equals("F") || choix.equals("P")){
       jeu.play(choix.charAt(0));
      out.write("\n");
      out.write("    Vous venez de jouer ");
      out.print( jeu.getLastHumain() );
      out.write(" et l'ordi ");
      out.print( jeu.getLastOrdi() );
      out.write("<br>\n");
      out.write("    ");

       } else { 
      out.write("\n");
      out.write("    Bien essayé mais ca ne marche pas<br>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    <br>\n");
      out.write("    Somme ");
      out.print( jeu.getPointsHumain() );
      out.write(' ');
      out.write('à');
      out.write(' ');
      out.print( jeu.getPointsOrdi() );
      out.write("<br>\n");
      out.write("    <br>\n");
      out.write("    ");
 if (!jeu.termine()) { 
      out.write("\n");
      out.write("    Vous jouez <a href=\"http://Ayou17:8080/vide/jeu.jsp?choix=F\">Face</a> ou <a href=\"http://Ayou17:8080/vide/jeu.jsp?choix=P\">Pile</a><br>\n");
      out.write("    ");
 }else{
       if (jeu.getPointsHumain()==10){ 
      out.write("\n");
      out.write("    <h2>Vous avez gagné :) </h2>\n");
      out.write("    ");
 }else{ 
      out.write("\n");
      out.write("    <h2>Vous avez perdu :( </h2>\n");
      out.write("    ");
 } 
    session.invalidate(); 
      out.write("\n");
      out.write("    <a href=\"http://Ayou17:8080/vide/jeu.jsp\">Rejouer ?</a><br>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </center>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
