/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2017-03-03 08:02:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import securite.Personne;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;
import java.sql.*;

public final class Maj_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang='fr'>\n");
      out.write("<head><meta charset='utf-8'><meta http-equiv='X-UA-Compatible' content='IE=edge'><meta name='viewport' content='width=device-width, initial-scale=1'>\n");
      out.write("<title>Page de login</title>\n");
      out.write("<link href='//getbootstrap.com/dist/css/bootstrap.min.css' rel='stylesheet'>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<title>Administration</title>\t\n");
      out.write("\t<!-- Bootstrap core CSS --><link href='//getbootstrap.com/dist/css/bootstrap.min.css' rel='stylesheet'>\n");
      out.write("\t\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\n");
      out.write("\t");
session = request.getSession(true);
	Personne p = (Personne)session.getAttribute("login");
	if (p==null) response.sendRedirect("Deconnection.jsp");
      out.write("\n");
      out.write("\t\n");
      out.write("\t<div class='container'>\n");
      out.write("\t<div class='page-header'>\n");
      out.write("\t<h1>Modifier vos informations</h1>\n");
      out.write("\t</div>\n");
      out.write("\t<div class='row'>\n");
      out.write("\t\t<div class='col-xs-12'>\n");
      out.write("\t\t     <form class='form-horizontal' method='get' action='Maj2.jsp'>\n");
      out.write("\t\t\t<div class='form-group'>\n");
      out.write("\t\t\t\t<label for='inputLogin' class='col-sm-2 control-label'>Login</label>\n");
      out.write("\t\t\t\t<div class='col-sm-10'>\n");
      out.write("\t\t\t\t<input type='text' class='form-control' readonly='readonly' name='login' value='");
      out.print(p.login);
      out.write("'>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t \t<div class='form-group'>\n");
      out.write("\t\t<label for='inputPassword' class='col-sm-2 control-label'>Mot de passe</label>\n");
      out.write("\t\t<div class='col-sm-10'>\n");
      out.write("\t\t<input type='text' class='form-control' id='inputPassword' name='mdp' value='");
      out.print(p.mdp);
      out.write("'>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class='form-group'>\n");
      out.write("\t\t\t<label for='inputNom' class='col-sm-2 control-label'>Nom</label>\n");
      out.write("\t\t\t<div class='col-sm-10'>\n");
      out.write("\t\t\t\t<input type='text' class='form-control' id='inputNom' name='nom' value='");
      out.print(p.nom);
      out.write("'>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class='form-group'>\n");
      out.write("\t\t\t<label for='inputPrenom' class='col-sm-2 control-label'>Prenom</label>\n");
      out.write("\t\t\t<div class='col-sm-10'>\n");
      out.write("\t\t\t\t<input type='text' class='form-control' id='inputPrenom' name='prenom' value='");
      out.print(p.prenom);
      out.write("'>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<input type='hidden' name='type' value='");
      out.print(p.role);
      out.write("'>\n");
      out.write("\t\t<div class='form-group'>\n");
      out.write("\t\t     <div class='col-sm-offset-2 col-sm-10'>\n");
      out.write("\t\t\t  <button type='submit' class='btn btn-primary'>Mettre a jour</button>\n");
      out.write("\t\t     </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<a href='Menu.jsp'><button class='btn btn-default'>Retour au menu</button></a>\t\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
