/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2017-01-11 09:29:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.HashMap;;

public final class mapage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 public class Panier{
    HashMap<Integer,Integer> map;
    public Panier(HashMap<Integer,Integer> m){
      this.map=m;
    }
    public void put(Integer a,Integer b){map.put(a,b);}
    public Integer get(Integer a){return map.get(a);}
    public void toHTML(){
      if (map.get(1)!=0){System.out.println("Table " + map.get(1));}
      if (map.get(2)!=0){System.out.println("Chaise "+ map.get(2));}
      if (map.get(3)!=0){System.out.println("Bureau "+ map.get(3));}
      if (map.get(4)!=0){System.out.println("Secretaire "+ map.get(4));}
      System.out.println("Secretaire "+ map.get(4));
    }
  }
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write(" \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title> Site </title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  ");
      out.write("\n");
      out.write("\n");
      out.write("  ");
 Panier l = (Panier)session.getAttribute("Panier");
     if (l==null){
       HashMap<Integer,Integer> m=new HashMap<Integer,Integer>();
       l = new Panier(m);
       l.put(1,0);l.put(2,0);l.put(3,0);l.put(4,0);
       session.setAttribute("Panier",l);
     }
     String id=request.getParameter("id");
     if(id!=null && id!=""){
       l.put(Integer.parseInt(id),l.get(Integer.parseInt(id))+1);
     }else{
        l.put(1,0);l.put(2,0);l.put(3,0);l.put(4,0);
     }
  
      out.write('\n');
      out.write(' ');
      out.write(' ');
 Class.forName("org.postgresql.Driver");
     String url = "jdbc:postgresql://psqlserv/n3p1";
     String nom = "lassallr";
     String mdp = "moi";
     Connection con = DriverManager.getConnection(url,nom,mdp);
     Statement stmt= con.createStatement();
     
      out.write("\n");
      out.write("    <h2>Panier</h2>\n");
      out.write("    ");
 l.toHTML(); 
      out.write("\n");
      out.write("    ");
 
      if (l.get(1)!=0){System.out.println("Table " + l.get(1));}
      if (l.get(2)!=0){System.out.println("Chaise "+ l.get(2));}
      if (l.get(3)!=0){System.out.println("Bureau "+ l.get(3));}
      if (l.get(4)!=0){System.out.println("Secretaire "+ l.get(4));} 
      out.write("\n");
      out.write("<br>   \n");
      out.write("<button type=\"button\" onclick=\"window.location.href='/vide/mapage.jsp'\">Vider le panier</button>\n");
      out.write("    <h2>Articles</h2>\n");
      out.write("    ");

      ResultSet rs = stmt.executeQuery("select * from produits;");
      while(rs.next()){
      out.write("\n");
      out.write("      <a href=mapage.jsp?id=");
      out.print( rs.getInt(1) );
      out.write('>');
      out.print( rs.getString(2) );
      out.write(" </a>\n");
      out.write("      <!-- ");
      out.print( rs.getInt(3) );
      out.write("  --><br>\n");
      out.write("      ");
 }
      con.close();
    
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
